### ISSUE TITLE
npm start does not work

### ISSUE THREAD

**Issue by akhenry** [shefalijoshi/telemetry-client#4]
The [readme file](https://github.com/shefalijoshi/telemetry-client/blob/master/README.md) references the command `npm start`, but a start script has not been defined in `package.json`. Instead, the correct command appears to be `npm run build`.

**Comment by shefalijoshi** [comment]
@akhenry npm start was to start the tutorial server. In the section below that it does say npm run build.

**Comment by akhenry** [comment]
@shefalijoshi You're right, my apologies, I completely misread the instructions.
