### ISSUE TITLE
Add reverse proxy for tutorial telemetry server

### ISSUE THREAD

**Issue by akhenry** [shefalijoshi/telemetry-client#6]
Right now running this client code involves modifying the tutorial telemetry server to add CORS headers. This is time consuming and fiddly for users who are not developers (eg. testers!).

The webpack-dev-server supports reverse proxying. The [webpack config](https://github.com/shefalijoshi/telemetry-client/blob/master/webpack.config.js) in this project could be modified to defined a reverse proxy for the openmct tutorial server running on the same port as the application, which would negate the need to add CORS heads to the tutorial server for this particular application. See the openmct-yamcs project for [an example](https://github.com/akhenry/openmct-yamcs/blob/master/webpack.config.js#L51) of reverse-proxying with webpack-dev-server.

**Comment by shefalijoshi** [comment]
Resolved by https://github.com/shefalijoshi/telemetry-client/commit/9df58f568d88efed581130189a20d03aea476c73
